<?php $link = $this->serverUrl() . $this->url('zfcuser/reset-password', array('id' => $this->id, 'token' => $this->token)); ?>
<h1>Reset your password</h1>
<p>You have received this email because you (or someone else) tried to log in to www.awesome.dev on <?= $this->time->format('d M Y \a\t H:i:s') ;?>.</p>
<p>If this was not you then you can ignore this message.</p>
<p>To reset your password, please click <a href="<?= $link; ?>">here</a>.</p>
