<?php 

    use Del\Cdn;
    use Del\Icon;

    echo $this->doctype(); 

?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Delboy Skeleton App ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= Cdn::bootstrapCssLink(); ?>
        <?= Cdn::fontAwesomeCssLink(); ?>
        <?= Cdn::jQueryUiCssLink(); ?>
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css')); ?>
        <?= Cdn::delCssLink(); ?>
        
        <!-- Scripts -->
        <?= Cdn::jQueryJavascript(); ?>
        <?= Cdn::bootstrapJavascript(); ?>
        <?= Cdn::jQueryUIJavascript(); ?>
        <?= $this->headScript()
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/zf2-logo.png') ?>" alt="Delboy1978uk"/>&nbsp;<?= $this->translate('Del Skeleton App') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') > 2015 ? '2015 - '.date('Y') : date('Y'); ?> delboy1978uk. <?= $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?= $this->inlineScript() ?>
    </body>
</html>
